import "./globals.css";
import { Metadata } from "next"; 
import StoreProvider from "./providers";


export const metadata: Metadata = {
  title: "Cardinal E School",
  description: "Generated by create next app",
  // prefetch: {
  //   images: true,
  //   scripts: true,
  //   styles: true
  // }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <head>
      <link rel="shortcut icon" href="/assets/img/favicon-logo.png" type="image/x-icon" />
    </head>
     <body>
      <StoreProvider>        
        {children}
        </StoreProvider>
    </body>
  </html>
  );
}
