import "./globals.css";
import { Metadata } from "next";
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Cardinal E School",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <Providers>{children}</Providers>
    </body>
  </html>
  );
}
