import "./globals.css";
import { Metadata } from "next"; 
import StoreProvider from "./providers";


export const metadata: Metadata = {
  title: "Cardinal E School",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <StoreProvider>        
        {children}
        </StoreProvider>
    </body>
  </html>
  );
}
