import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Cardinal E School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <div className="min-h-screen">
        {children}
        </div>
    </>
  );
}
