import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
    <head>
      <link rel="shortcut icon" href="/assets/img/favicon-logo.png" type="image/x-icon" />
    </head>
     <body
        className={`antialiased`}
      >
        <div className="min-h-screen">
        {children}
        </div>
      </body>
    </html>
  );
}
