import "../globals.css";
import PublicNavbar from "@/components/public/Navbar";
import PublicFooter from "@/components/public/Footer"; 
import { Metadata } from "next"; 
// import StoreProvider from "../providers";


export const metadata: Metadata = {
  title: "Cardinal E School",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <> 
     <PublicNavbar/>
        <div className="min-h-screen"> 
        {children} 
        </div>
        <PublicFooter/>
    </>
  );
}
